### ISSUE TITLE
fx2ait has torch version limitations?

### ISSUE THREAD

**Issue by fwd4** [facebookincubator/AITemplate#850]
I'm trying to work on torch version 1.10 + cuda 11.4, we are on a drive devkit agx orin, so cuda version is pretty much fixed. And I came across compilation errors when I try to build fx2ait:
```
python setup.py install
```

And I got the following compilation errors:
```
In file included from /workspace/AITemplate/fx2ait/fx2ait/csrc/AITModel.cpp:1:
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModel.h: In member function ‘void torch::aitemplate::AITModel::profile(std::vector<at::Tensor>, const string&, int64_t)’:
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModel.h:40:5: error: ‘TORCH_CHECK_GE’ was not declared in this scope; did you mean ‘TORCH_CHECK’?
   40 |     TORCH_CHECK_GE(num_iters, 0);
      |     ^~~~~~~~~~~~~~
      |     TORCH_CHECK
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In member function ‘void torch::aitemplate::AITModelImpl::allocateOutputs(std::vector<c10::intrusive_ptr<c10::StorageImpl> >&, std::vector<AITData>&, std::vector<std::vector<long int> >&, std::vector<long int*>&,
const c10::Device&)’:
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:256:30: error: ‘computeStorageNbytesContiguous’ is not a member of ‘at::detail’; did you mean ‘computeStorageNbytes’?
  256 |     size_bytes = at::detail::computeStorageNbytesContiguous(
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              computeStorageNbytes
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In member function ‘std::vector<at::Tensor> torch::aitemplate::AITModelImpl::processOutputs(std::vector<c10::intrusive_ptr<c10::StorageImpl> >&, const std::vector<std::vector<long int> >&)’:
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:302:35: error: ‘class at::TensorBase’ has no member named ‘to’
  302 |       outputs.emplace_back(output.to(*floating_point_output_dtype_));
      |                                   ^~
make[2]: *** [CMakeFiles/ait_model.dir/build.make:76: CMakeFiles/ait_model.dir/fx2ait/csrc/AITModel.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp: In function ‘c10::ScalarType torch::aitemplate::{anonymous}::AITemplateDtypeToTorchDtype(AITemplateDtype)’:
/workspace/AITemplate/fx2ait/fx2ait/csrc/AITModelImpl.cpp:206:1: warning: control reaches end of non-void function [-Wreturn-type]
  206 | }
```

**Comment by ymwangg** [comment]
Yes, you need a torch version later than https://github.com/pytorch/pytorch/pull/97647.

**Comment by fwd4** [comment]
Thanks for reply, I now begin with higher version of cuda/torch. 

There is another problem that I got: is there any chance I can use fx2ait flow, starting with an onnx model, let's say a very simple res18 onnx model?

> Yes, you need a torch version later than [pytorch/pytorch#97647](https://github.com/pytorch/pytorch/pull/97647).

**Comment by kadeng** [comment]
fx2ait works with torch.fx, so unless you first somehow translate your onnx model to pytorch, it would not work.
